name: Create release
on:
  push:
    tags: '*'

jobs:
  build_and_release:
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
          # - arch: armv6
          #   distro: jessie
          - arch: armv7
            distro: ubuntu_latest
          # - arch: ppc64le
          #   distro: ubuntu_latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Building x64 limon
        run: |
          mkdir -p ${PWD}/artifacts
          make
          cp bin/limon ${PWD}/artifacts/limon.x64

      - name: Build limon artifacts for other arches
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          dockerRunArgs: |
              --volume "${PWD}/artifacts:/artifacts"
          env: |
              artifact_name: limon.${{ matrix.arch }}
          # Install some dependencies in the container.
          install: |
            apt-get update -q -y
            apt-get install -q -y git make gcc
          run: |
              make
              cp bin/limon "/artifacts/${artifact_name}"
              echo "Produced artifact at /artifacts/${artifact_name}"

      - name: Publish artifacts
        uses: actions/upload-artifact@v3
        with:
          name: limon binaries
          path: artifacts/*

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*
